const categoriesData = [
  {
    name: 'Bridal Sets',
    slug: 'bridal-sets',
    description: 'Bespoke royal bridal sets, kundan haars, chokers and heirloom wedding jewellery.',
    image: {
      url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-bridal-sets',
    },
    order: 1,
    isActive: true,
  },
  {
    name: 'Diamond Jewellery',
    slug: 'diamond-jewellery',
    description: 'Certified VVS-EF clarity natural and solitaire diamond collections with luminous brilliance.',
    image: {
      url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-diamond-jewellery',
    },
    order: 2,
    isActive: true,
  },
  {
    name: 'Gold Necklaces',
    slug: 'gold-necklaces',
    description: '22K 916 Hallmarked mastercrafted gold necklaces, antique temple chokers and Calcutta filigree.',
    image: {
      url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-gold-necklaces',
    },
    order: 3,
    isActive: true,
  },
  {
    name: 'Bangles & Kadas',
    slug: 'bangles-kadas',
    description: 'Traditional 22K gold patlas, antique temple kadas, and diamond-studded bangles.',
    image: {
      url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-bangles-kadas',
    },
    order: 4,
    isActive: true,
  },
  {
    name: 'Rings & Solitaires',
    slug: 'rings-solitaires',
    description: 'Precious engagement rings, eternity bands, solitaire cocktail rings and men’s signature bands.',
    image: {
      url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-rings-solitaires',
    },
    order: 5,
    isActive: true,
  },
  {
    name: 'Earrings & Jhumkas',
    slug: 'earrings-jhumkas',
    description: 'Heirloom Polki chandbalis, cascading jhumkas, and timeless diamond studs.',
    image: {
      url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-earrings-jhumkas',
    },
    order: 6,
    isActive: true,
  },
  {
    name: 'Mangalsutras & Pendants',
    slug: 'mangalsutras-pendants',
    description: 'Modern sacred mangalsutras and handcrafted auspicious pendants in 18K and 22K gold.',
    image: {
      url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-mangalsutras-pendants',
    },
    order: 7,
    isActive: true,
  },
  {
    name: 'Gold Coins & Bars',
    slug: 'gold-coins-bars',
    description: '24K 999.9 pure gold investment coins and minted bullion with tamper-proof certification.',
    image: {
      url: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80',
      public_id: 'cat-gold-coins-bars',
    },
    order: 8,
    isActive: true,
  },
];

const collectionsData = [
  {
    name: 'Royal Rajputana Heritage',
    slug: 'royal-rajputana-heritage',
    tagline: 'Imperial Jadau & Polki Masterpieces Inspired by Princely Dynasties',
    description: 'Each piece in this heritage collection embodies century-old meenakari enamelling and uncut syndicate polki set in warm 22K gold.',
    bannerImage: {
      url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85',
      public_id: 'col-royal-rajputana',
    },
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'The Solitaire Symphony',
    slug: 'the-solitaire-symphony',
    tagline: 'GIA & IGI Certified Flawless Diamonds',
    description: 'Modern architectural silhouettes crafted in 18K white and yellow gold, highlighting brilliant-cut solitaires with unmatched fire.',
    bannerImage: {
      url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
      public_id: 'col-solitaire-symphony',
    },
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Aashirwaad Bridal Vows',
    slug: 'aashirwaad-bridal-vows',
    tagline: 'Timeless Grandeur for the Modern Indian Bride',
    description: 'Complete wedding trousseau sets featuring multilayered haars, delicate mathapattis, nath, and matching jhumkis.',
    bannerImage: {
      url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1200&q=85',
      public_id: 'col-aashirwaad-bridal',
    },
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Nizam Polki & Jadau',
    slug: 'nizam-polki-jadau',
    tagline: 'Pure Hyderabadi Aristocracy & Basra Pearl Accents',
    description: 'Intricately handcrafted unheated gemstones, emerald beads, and untreated polki diamonds reflecting pure Deccan craftsmanship.',
    bannerImage: {
      url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85',
      public_id: 'col-nizam-polki',
    },
    isActive: true,
    isFeatured: false,
  },
];

const productsData = [
  {
    name: 'The Maharani Imperial Polki Choker Set',
    slug: 'maharani-imperial-polki-choker-set',
    sku: 'NSJ-BRD-001',
    categorySlug: 'bridal-sets',
    collectionSlug: 'royal-rajputana-heritage',
    description: 'A breathtaking bridal statement featuring uncut Syndicate Polki diamonds, hand-strung natural Zambian emerald beads, and intricate red Meenakari reverse enamelling in 22K yellow gold. Comes with matching royal Chandbali earrings and Maang Tikka.',
    price: 685000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '118.50 grams',
    stoneType: 'Polki / Uncut Diamond',
    stoneWeight: '28.40 carats (Polki + Emeralds)',
    stock: 2,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-brd-001-1',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-brd-001-2',
        isPrimary: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-brd-001-3',
        isPrimary: false,
      },
    ],
    seoTitle: 'Maharani Imperial Polki Choker Set | Sanjay Jewellers',
    seoDescription: 'Handcrafted 22K gold imperial bridal Polki choker set with Zambian emeralds by Sanjay Jewellers.',
  },
  {
    name: 'Royal Solitaire Pavé Diamond Ring',
    slug: 'royal-solitaire-pave-diamond-ring',
    sku: 'NSJ-RNG-101',
    categorySlug: 'rings-solitaires',
    collectionSlug: 'the-solitaire-symphony',
    description: 'An exceptional 2.05 carat round brilliant-cut solitaire diamond held in a six-prong platinum crown, complemented by a micro-pavé set 18K yellow gold band. Certified IGI / GIA with triple excellent cut.',
    price: 380000,
    isPriceOnRequest: false,
    goldPurity: '18K',
    goldWeight: '5.80 grams',
    stoneType: 'Diamond',
    stoneWeight: '2.45 carats total (2.05ct center)',
    stock: 4,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-rng-101-1',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-rng-101-2',
        isPrimary: false,
      },
    ],
    seoTitle: 'Royal Solitaire Pavé Diamond Ring | Sanjay Jewellers',
    seoDescription: 'Bespoke 2.05 Carat Solitaire Engagement Ring in 18K Gold and Platinum.',
  },
  {
    name: 'Heritage Temple Gold Nakshi Necklace',
    slug: 'heritage-temple-gold-nakshi-necklace',
    sku: 'NSJ-NCK-201',
    categorySlug: 'gold-necklaces',
    collectionSlug: 'royal-rajputana-heritage',
    description: 'Classic 22K 916 hallmarked pure yellow gold necklace handcrafted with deep hand-chased Nakshi carving depicting Goddess Lakshmi and floral motifs, accented with Burmese rubies and South Sea pearls.',
    price: 495000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '84.20 grams',
    stoneType: 'Ruby',
    stoneWeight: '4.80 carats natural rubies',
    stock: 1,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-nck-201-1',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-nck-201-2',
        isPrimary: false,
      },
    ],
    seoTitle: 'Heritage Temple Gold Nakshi Necklace | Sanjay Jewellers',
    seoDescription: 'Authentic 22K 916 Hallmarked Temple Gold Nakshi Necklace for weddings.',
  },
  {
    name: 'Empress Polki & Pearl Chandbali Earrings',
    slug: 'empress-polki-pearl-chandbali-earrings',
    sku: 'NSJ-EAR-301',
    categorySlug: 'earrings-jhumkas',
    collectionSlug: 'nizam-polki-jadau',
    description: 'Royal crescent-shaped Chandbali earrings studded with uncut Syndicate polki, natural cabochon emeralds, and finished with delicate Basra seed pearl tassels in 22K hallmarked gold.',
    price: 245000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '38.40 grams',
    stoneType: 'Polki / Uncut Diamond',
    stoneWeight: '12.60 carats',
    stock: 3,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-ear-301-1',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-ear-301-2',
        isPrimary: false,
      },
    ],
    seoTitle: 'Empress Polki & Pearl Chandbali Earrings | Sanjay Jewellers',
    seoDescription: '22K Gold Polki & Pearl Chandbalis by Sanjay Jewellers.',
  },
  {
    name: 'Regal 22K Antique Filigree Kada Pair',
    slug: 'regal-22k-antique-filigree-kada-pair',
    sku: 'NSJ-BNG-401',
    categorySlug: 'bangles-kadas',
    collectionSlug: 'royal-rajputana-heritage',
    description: 'A pair of magnificent screw-lock antique finished 22K gold kadas featuring intricate jali filigree work, beaded edges, and floral clasp terminals.',
    price: 360000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '62.00 grams (pair)',
    stoneType: 'None / Plain Gold',
    stoneWeight: '0',
    stock: 2,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-bng-401-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Regal 22K Antique Filigree Kada Pair | Sanjay Jewellers',
    seoDescription: 'Pure 22K gold antique handcrafted bridal bangles pair.',
  },
  {
    name: 'The Crown Princess Diamond Collar Necklace',
    slug: 'the-crown-princess-diamond-collar-necklace',
    sku: 'NSJ-DIA-501',
    categorySlug: 'diamond-jewellery',
    collectionSlug: 'the-solitaire-symphony',
    description: 'An ethereal cascading collar necklace composed of over 340 round brilliant and marquise diamonds with VVS clarity and E-F color grading, set in luminous 18K white gold.',
    price: 920000,
    isPriceOnRequest: true,
    goldPurity: '18K',
    goldWeight: '68.50 grams',
    stoneType: 'Diamond',
    stoneWeight: '14.80 carats VVS-EF',
    stock: 1,
    availability: 'Made to Order',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: false,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-dia-501-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Crown Princess Diamond Collar Necklace | Sanjay Jewellers',
    seoDescription: 'High luxury 14.80ct Diamond bridal necklace in 18K gold.',
  },
  {
    name: 'Auspicious Solitaire Diamond Mangalsutra',
    slug: 'auspicious-solitaire-diamond-mangalsutra',
    sku: 'NSJ-MNG-601',
    categorySlug: 'mangalsutras-pendants',
    collectionSlug: 'the-solitaire-symphony',
    description: 'Contemporary sacred mangalsutra featuring a certified 0.75ct center solitaire diamond flanked by twin infinity arches and hand-strung black onyx beads in 18K yellow gold.',
    price: 155000,
    isPriceOnRequest: false,
    goldPurity: '18K',
    goldWeight: '8.40 grams',
    stoneType: 'Diamond',
    stoneWeight: '0.95 carats total',
    stock: 5,
    availability: 'In Stock',
    isFeatured: false,
    isNewArrival: true,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-mng-601-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Auspicious Solitaire Diamond Mangalsutra | Sanjay Jewellers',
    seoDescription: 'Modern 18K Gold and Diamond Mangalsutra by Sanjay Jewellers.',
  },
  {
    name: 'Goddess Lakshmi 24K Pure Gold Coin (10g)',
    slug: 'goddess-lakshmi-24k-pure-gold-coin-10g',
    sku: 'NSJ-COI-701',
    categorySlug: 'gold-coins-bars',
    collectionSlug: null,
    description: '999.9 Fine purity 24K Swiss-grade minted gold coin with embossed divine Goddess Lakshmi motif. Tamper-evident certified blister packaging with assay serial number.',
    price: 74500,
    isPriceOnRequest: false,
    goldPurity: '24K',
    goldWeight: '10.00 grams',
    stoneType: 'None / Plain Gold',
    stoneWeight: '0',
    stock: 25,
    availability: 'In Stock',
    isFeatured: false,
    isNewArrival: false,
    isBestseller: true,
    isBridal: false,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-coi-701-1',
        isPrimary: true,
      },
    ],
    seoTitle: '24K 999.9 Pure Gold Coin 10 Grams | Sanjay Jewellers',
    seoDescription: 'BIS certified 24 Karat 999.9 pure gold coin for investment and gifting.',
  },
  {
    name: 'Emerald & Diamond Princess Ring',
    slug: 'emerald-and-diamond-princess-ring',
    sku: 'NSJ-RNG-102',
    categorySlug: 'rings-solitaires',
    collectionSlug: 'the-solitaire-symphony',
    description: 'An intense vivid green Colombian emerald cut center stone embraced by a sparkling halo of baguette and round brilliant diamonds in 18K yellow gold.',
    price: 210000,
    isPriceOnRequest: false,
    goldPurity: '18K',
    goldWeight: '6.20 grams',
    stoneType: 'Emerald',
    stoneWeight: '3.10 carats (Emerald) + 0.85ct (Diamonds)',
    stock: 3,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: false,
    isBridal: false,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-rng-102-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Emerald & Diamond Princess Ring | Sanjay Jewellers',
    seoDescription: 'Colombian emerald cocktail ring in 18K gold.',
  },
  {
    name: 'Jodha Royal Kundan Bridal Haram Set',
    slug: 'jodha-royal-kundan-bridal-haram-set',
    sku: 'NSJ-BRD-002',
    categorySlug: 'bridal-sets',
    collectionSlug: 'aashirwaad-bridal-vows',
    description: 'Grand three-layered Raani Haar studded with traditional foil-backed Kundan glass and precious ruby drops, accompanied by heavy Kundan jhumkas and Haathphool.',
    price: 540000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '96.80 grams',
    stoneType: 'Kundan',
    stoneWeight: '22.50 carats',
    stock: 2,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-brd-002-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Jodha Royal Kundan Bridal Haram Set | Sanjay Jewellers',
    seoDescription: 'Heirloom 22K Kundan bridal raani haar set for weddings.',
  },
  {
    name: 'Sparkling 18K Diamond Tennis Bracelet',
    slug: 'sparkling-18k-diamond-tennis-bracelet',
    sku: 'NSJ-BNG-402',
    categorySlug: 'bangles-kadas',
    collectionSlug: 'the-solitaire-symphony',
    description: 'A continuous line of 52 matching brilliant cut diamonds in a secure 4-prong box catch setting crafted in 18K white gold. Effortless luxury for every day.',
    price: 295000,
    isPriceOnRequest: false,
    goldPurity: '18K',
    goldWeight: '14.20 grams',
    stoneType: 'Diamond',
    stoneWeight: '5.20 carats VVS-GH',
    stock: 3,
    availability: 'In Stock',
    isFeatured: true,
    isNewArrival: true,
    isBestseller: false,
    isBridal: false,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-bng-402-1',
        isPrimary: true,
      },
    ],
    seoTitle: '18K Diamond Tennis Bracelet | Sanjay Jewellers',
    seoDescription: '5.20 Carat diamond tennis bracelet in 18K gold.',
  },
  {
    name: 'Heritage Ruby Floral Gold Jhumka',
    slug: 'heritage-ruby-floral-gold-jhumka',
    sku: 'NSJ-EAR-302',
    categorySlug: 'earrings-jhumkas',
    collectionSlug: 'royal-rajputana-heritage',
    description: 'Grand bell-shaped 22K gold jhumkas featuring delicate filigree floral studs, ruby cabochons, and dangling golden ghungroo clusters.',
    price: 185000,
    isPriceOnRequest: false,
    goldPurity: '22K',
    goldWeight: '29.50 grams',
    stoneType: 'Ruby',
    stoneWeight: '2.80 carats',
    stock: 4,
    availability: 'In Stock',
    isFeatured: false,
    isNewArrival: true,
    isBestseller: true,
    isBridal: true,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=85',
        public_id: 'prod-ear-302-1',
        isPrimary: true,
      },
    ],
    seoTitle: 'Heritage Ruby Floral Gold Jhumka | Sanjay Jewellers',
    seoDescription: '22K Hallmarked gold jhumka earrings with ruby accents.',
  },
];

const sampleEnquiries = [
  {
    name: 'Ananya Sharma',
    phone: '+91 98201 23456',
    email: 'ananya.sharma@example.com',
    productName: 'The Maharani Imperial Polki Choker Set',
    productSku: 'NSJ-BRD-001',
    productUrl: 'http://localhost:5173/product/maharani-imperial-polki-choker-set',
    message: 'Hello, I am interested in trying this Polki choker set for my wedding in December. Can we customize the emerald beads to rubies?',
    status: 'New',
    notes: 'Interested in December wedding bridal consultation. Requested ruby bead customization.',
  },
  {
    name: 'Rajesh Singhania',
    phone: '+91 98450 98765',
    email: 'singhania.rajesh@example.com',
    productName: 'Royal Solitaire Pavé Diamond Ring',
    productSku: 'NSJ-RNG-101',
    productUrl: 'http://localhost:5173/product/royal-solitaire-pave-diamond-ring',
    message: 'Please share the GIA certificate copy and current best quotation for ring size 14.',
    status: 'Contacted',
    notes: 'Sent certificate copy over WhatsApp. Awaiting showroom visit confirmation.',
  },
  {
    name: 'Pooja Kulkarni',
    phone: '+91 97654 11223',
    email: 'pooja.k@example.com',
    productName: 'The Crown Princess Diamond Collar Necklace',
    productSku: 'NSJ-DIA-501',
    productUrl: 'http://localhost:5173/product/the-crown-princess-diamond-collar-necklace',
    message: 'Looking for the price on request and lead time for delivery.',
    status: 'Follow-up',
    notes: 'Quote provided. Follow-up scheduled for next Tuesday.',
  },
];

const sampleAppointments = [
  {
    name: 'Meera Deshmukh',
    phone: '+91 99887 66554',
    email: 'meera.deshmukh@example.com',
    date: '2026-09-20',
    timeSlot: '03:00 PM - 04:30 PM',
    jewelleryInterest: 'Bridal Sets',
    consultationType: 'In-Showroom VIP Experience',
    message: 'Family bridal jewellery shopping for 3 upcoming wedding events.',
    status: 'Confirmed',
    notes: 'Reserved VIP Private Viewing Room 1. Kept Polki and Kundan bridal catalogue ready.',
  },
  {
    name: 'Vikramaditya Roy',
    phone: '+91 98112 33445',
    email: 'v.roy@example.com',
    date: '2026-09-22',
    timeSlot: '11:30 AM - 01:00 PM',
    jewelleryInterest: 'Solitaire Rings',
    consultationType: 'Virtual Video Consultation',
    message: 'Looking for bespoke diamond engagement ring consultation.',
    status: 'Pending',
    notes: 'Zoom link to be shared 24 hours prior.',
  },
];

module.exports = {
  categoriesData,
  collectionsData,
  productsData,
  sampleEnquiries,
  sampleAppointments,
};
